[package]
name = "siren"
version = "1.1.1"
authors = ["Alessio Biancalana <dottorblaster@gmail.com>"]
description = "Your friendly neighborhood monitoring CLI tool."
homepage = "https://github.com/dottorblaster/siren"
repository = "https://github.com/dottorblaster/siren"
readme = "README.md"
license = "MIT"

[dependencies]
ansi_term = "0.11.0"
clap = "~2.32.0"
serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.82"
